project_ms/core/urls.py
from django.shortcuts import redirect
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name= 'user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name= 'user/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_ms/project_ms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace='core')),
    path('user/', include("user.urls", namespace='user')),
    path('project/', include("projects.urls", namespace='projects')),
    path('views/', include("views.urls", namespace='views')),
]

project_ms/user/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('update-profile/<int:id>', views.UpdateProfile, name='update-profile'),
]

project_ms/projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=80)
    project_lead = models.ForeignKey(User, on_delete=models.CASCADE)
    assign = models.ManyToManyField(User, related_name="project_assign")
    # efforts = models.DurationField()
    status = models.CharField(max_length=7, choices=status, default=1)
    complete_per = models.FloatField(max_length=2, validators = [MinValueValidator(0), MaxValueValidator(100)])
    description = models.TextField(blank=True)
    deadline = models.DateField()

    add_date = models.DateField(auto_now_add=True)
    upd_date = models.DateField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return (self.name)


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="task_project_assign")
    assign = models.ManyToManyField(User, related_name="task_assign")
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)
    description = models.TextField(blank=True)
    deadline = models.DateField()

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)

# class ProjectAssign(models.Model):
#     user_id = models.ForeignKey(User, on_delete=models.CASCADE)
#     project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

#     class Meta:
#         db_table = 'project_assign_user'

#     def __str__(self) -> str:
#         return f"{self.user_id} with project {self.project_id}"

project_ms/user/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

employment_type = (
    ('1', 'Employee'),
    ('2', 'Intern'),
)

# Create your models here.
class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=8, choices=employment_type, default = 1)
    img  = models.ImageField(upload_to='core/avatar', blank=True, default='core/avatar/blank_profile.png')

    def __str__(self):
        return str(self.user.email)

project_ms/user/forms.py
from email.policy import default
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


employment_type = (
    ('1', 'Employee'),
    ('2', 'Intern'),
)

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='E-mail', required=True)
    type = forms.ChoiceField(choices=employment_type)

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'type',
            'password1',
            'password2',
        }

        labels = {
            'username' : 'Username',
            'first_name': 'Name',
            'last_name': 'Last Name',
            'password1' : 'Password',
            'password2' : 'Confirm Password',
        }
    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.type = self.cleaned_data['type']
        user.email = self.cleaned_data['email']
        em_type = self.cleaned_data['type']

        if commit:
            user.save()
            user_profile = UserProfile.objects.create(user=user, type = em_type)
            user_profile.save()

        return user

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['type'].widget.attrs['class'] = 'form-control'
        self.fields['type'].widget.attrs['placeholder'] = 'Employment-Type'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Retype Password'
        
        
class ProfilePictureForm(forms.Form):
    img = forms.ImageField()
    class Meta:
        model = UserProfile
        fields = ['img']

    def save(self, request, commit=True):
        user = request.user.userprofile_set.first()
        user.img = self.cleaned_data['img']

        if commit:
            user.save()

        return user

    def __init__(self, *args, **kwargs):
        super(ProfilePictureForm, self).__init__(*args, **kwargs)
        self.fields['img'].widget.attrs['class'] = 'custom-file-input'
        self.fields['img'].widget.attrs['id'] = 'validatedCustomFile'

class ProfileUpdateForm(forms.ModelForm):

    email = forms.EmailField(label='E-mail', required=True)
    type = forms.ChoiceField(choices=employment_type)

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'type',
            # 'password1',
            # 'password2',
        }

        labels = {
            'username' : 'Username',
            'first_name': 'Name',
            'last_name': 'Last Name',
            # 'password1' : 'Password',
            # 'password2' : 'Confirm Password',
        }
    def save(self, commit=True):
        user = super(ProfileUpdateForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.type = self.cleaned_data['type']
        user.email = self.cleaned_data['email']
        em_type = self.cleaned_data['type']
        print(em_type)

        if commit:
            user.save()
            user_profile = UserProfile.objects.filter(user_id = user.id).update(user=user, type = em_type)
            # user_profile = UserProfile.objects.update(user=user, type = em_type)
            # user_profile.save()

        return user

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['type'].widget.attrs['class'] = 'form-control'
        self.fields['type'].widget.attrs['placeholder'] = 'Employment-Type'
        # self.fields['password1'].widget.attrs['class'] = 'form-control'
        # self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        # self.fields['password2'].widget.attrs['class'] = 'form-control'
        # self.fields['password2'].widget.attrs['placeholder'] = 'Retype Password'

project_ms/user/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from .forms import UserRegisterForm, ProfilePictureForm, ProfileUpdateForm
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.success(request, f" Account created for {username}!")
            return redirect('/user/profile')
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form' : form})

@login_required
def profile(request):
    if request.method == 'POST':
        img_form = ProfilePictureForm(request.POST, request.FILES)
        context = {'img_form' : img_form }
        if img_form.is_valid():
            img_form.save(request)
            updated = True
            context = {'img_form' : img_form, 'updated' : updated }
            return render(request, 'user/profile.html', context)
        else:
            return render(request, 'user/profile.html', context)
    else:
        img_form = ProfilePictureForm()
        context = {'img_form' : img_form }
        return render(request, 'user/profile.html', context)


@login_required
def UpdateProfile(request, id):
    if request.method == 'POST':
        obj = User.objects.get(pk = id)
        # print(obj)
        u_form = ProfileUpdateForm(request.POST, instance=obj)
        context = {'form': u_form}
        if u_form.is_valid():
            u_form.save()
            messages.success(request, ('Profile updated successfully'))
            return redirect(reverse('user:profile'))
        else:
            return render(request, 'user/update-profile.html', context)
    else:
        obj = User.objects.get(pk = id)
        u_form = ProfileUpdateForm(instance=obj)
        context = {
            'form': u_form,
        }
        return render(request,'user/update-profile.html', context)

project_ms/user/templates/user/login.html
{% extends "core/base.html" %}
{% block title%} Login {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

{% if user.is_authenticated %}
<div class="container">
    <div class="jumbotron">
      <h1>ALREADY LOGGED IN</h1>
      <br>
      <hr>
      <p>Go to <a href="{% url 'core:index' %}">Home Page</a></p>
  </div>
{% else %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Log In
                </button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Create an Account? <a class="ml-2" href="{% url 'user:register' %}">Sign Up</a>
            </small>
        </div>
    </div>
    {% endif %}
{% endblock %}

project_ms/user/templates/user/logout.html
{% extends "core/base.html" %}
{% block title%} Logout {% endblock %}
{% block content %}
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'core:login' %}">LogIn again</a>
            </small>
        </div>

{% endblock %}

project_ms/user/templates/user/profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Profile</li>
{% endblock breadcrumb%}

{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}
<div class="container-fluid">
    <div id="ui-view" style="opacity: 1;">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-12">
                    <div class="social-box" style="height:110%">
                        <div class="card">
                            <div class="card-body">
                                <div class="media">
                                  <!-- <img class="rounded-circle account-img" src="{{ logged_user.img.url }}"> -->
                                  <div class="media-body">
                                    <h2 class="account-heading">Welcome {{ user.username }}</h2>
                                    <p class="text-secondary">{{ user.email }}</p>
                                  </div>
                                </div>
                                <img src="{{ logged_user.img.url }}" class="img-avatar m-4" alt="{{ user }}" width="20%">
                                <br>
                                <form action="" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="custom-file col-md-4">
                                        {{ img_form.img }}
                                        <label class="custom-file-label btn-sm" for="validatedCustomFile">Update picture...</label>
                                        <div>
                                            <button class="btn btn-primary btn-sm my-2" type="submit">Upload</button>
                                        </div>
                                    </div>
                                </form>
                                <a href="/user/update-profile/{{ user.id }}">
                                    <button class="btn btn-primary btn-sm my-2" type="submit">Update Profile</button>
                                </a>
                                    <!-- <li>
                                        <strong>{{ logged_user.user.project_set.all.count }}</strong>
                                        <span>projects</span>
                                    </li> -->
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-5">
                <div class="col-12">
                    <div class="social-box">
                        <ul class="mt-3">
                            <li><span>Assigned Projects:
                                    {% for project in logged_user.user.project_set.all %}
                                        <a href="">{{ project.name }},</a>
                                    {% endfor %}
                                </span>
                            </li>
                        </ul>
                        <ul>
                            <li><span>Name: <a href="">{{ logged_user.user.get_full_name }}</a></span></li>
                            <li><span>e-mail: <span class="text-blue text-lowercase">{{ logged_user.user.email }}</span></span>
                            </li>
                        </ul>
                        <ul>
                            <li><span>Date joined: <span class="text-blue">{{ logged_user.user.date_joined }}</span></span></li>
                            <li><span>Last login: <span class="text-blue">{{ logged_user.user.last_login }}</span></span></li>
                        </ul>

                        <ul>
                            <li><span>Type: 
                                {% if logged_user.type == '1' %}
                                <span class="text-blue">Employee</span></span></li>
                                {% else %}
                                <span class="text-blue">Intern</span></span></li>
                                {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project_ms/user/templates/user/register.html
{% extends 'core/base.html' %}
{% load static %}
{% block title%} Register {% endblock %}
{% block breadcrumb %}
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item">Users</li>
<li class="breadcrumb-item active">Create New User</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container animated fadeIn">
    <div class="row justify-content-center">
        <div class="col-7">
            <div class="card-group p-5">
                <div class="card p-5 mb-5">
                    <div class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                                {{ message }}
                            </div>
                            {% endfor %}
                        {% endif %}
                        {% csrf_token %}
                        <h1>Register Yourself</h1>
                        <p class="text-muted">Create your Account here</p>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group">
                                    {{ form.username }}
                                    <div class="input-group-append">
                                        <span class="input-group-text">@</span>
                                    </div>
                                    {% if form.username.errors %}
                                    <ol>
                                        {% for error in form.username.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                        {% endfor %}
                                    </ol>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    {{ form.first_name }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                                    </div>
                                    {% if form.first_name.errors %}
                                    <ol>
                                        {% for error in form.first_name.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                        {% endfor %}
                                    </ol>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    {{ form.last_name }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                                    </div>
                                    {% if form.last_name.errors %}
                                    <ol>
                                        {% for error in form.last_name.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                        {% endfor %}
                                    </ol>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    {{ form.email }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                                    </div>
                                    {% if form.email.errors %}
                                    <ol>
                                        {% for error in form.email.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                        {% endfor %}
                                    </ol>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    {{ form.type }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                                    </div>
                                    {% if form.type.errors %}
                                    <ol>
                                        {% for error in form.type.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                        {% endfor %}
                                    </ol>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    {{ form.password1 }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-key"></i></span>
                                    </div>
                                    {% if form.password1.errors %}
                                    <ol>
                                        {% for error in form.password1.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                        {% endfor %}
                                    </ol>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    {{ form.password2 }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-key"></i></span>
                                    </div>

                                </div>
                                {% if form.password2.errors %}
                                <ol>
                                    {% for error in form.password2.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                </ol>
                                {% endif %}
                            </div>

                            <div class="">
                                <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-dot-circle-o"></i>
                                    Submit</button>
                                <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i>
                                    Reset</button>
                            </div>
                        </form>

                <div>
                    <br>
                    <hr>
                    <p class="text-muted">
                        Already have an Account? <a class="ml-2" href="{% url 'core:login' %}">Sign In</a>
                    </p>
                </div>
                        {{ form.errors }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}